export const products = [
  {
    id: 1,
    title: "Fjallraven - Foldsack No. 1 Backpack",
    price: 109.95,
    description: "Perfect pack for everyday use and walks in the forest...",
    category: "Backpack",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    rating: { rate: 3.9, count: 120 },
  },
  {
    id: 2,
    title: "Mens Casual Premium Slim Fit T-Shirts",
    price: 22.3,
    description: "Slim-fitting style, contrast raglan long sleeve...",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    rating: { rate: 4.1, count: 259 },
  },
  {
    id: 3,
    title: "Mens Cotton Jacket",
    price: 55.99,
    description: "Great outerwear jackets for Spring/Autumn/Winter...",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    rating: { rate: 4.7, count: 500 },
  },
    {
    id: 4,
    title: "Platinum Blue Denim",
    price: 440.0,
    description: "Casual wear denim for all day use.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.5, count: 210 },
  },
  {
    id: 5,
    title: "Mens Casual Slim Fit",
    price: 15.99,
    description: "The color could be slightly different on screen...",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    rating: { rate: 2.1, count: 430 },
  },
  {
    id: 6,
    title: "T-Shirt Round Neck",
    price: 18.99,
    description: "Soft cotton, regular fit and comfort...",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    rating: { rate: 4.3, count: 310 },
  },
  {
    id: 7,
    title: "Classic Blue Denim",
    price: 40.0,
    description: "Casual wear denim for all day use.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.5, count: 210 },
  },

  {
    id: 8,
    title: "Slim Fit Jeans",
    price: 32.5,
    description: "Comfort and stretch for a good fit.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    rating: { rate: 4.2, count: 170 },
  },
  {
    id: 9,
    title: "Full Sleeve Shirt",
    price: 29.99,
    description: "Formal shirt for office or meetings.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    rating: { rate: 4.4, count: 185 },
  },
  {
    id: 10,
    title: "Winter Hoodie",
    price: 45.0,
    description: "Cozy and warm with inner fleece lining.",
    category: "jewelery",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    rating: { rate: 4.6, count: 250 },
  },
];
